stages:
  - pre-build
  - build
  - check

.base:
  tags:
    - d13-runner

.php:
  image: "$TWINT_SDK_PHP_IMAGE_BASE-$PHP_VERSION"
  parallel:
    matrix:
      - { PHP_VERSION: &php_version [ "8.1", "8.2", "8.3" ] }
  extends: .base

.php-with-high-low-dependencies:
  parallel:
    matrix:
      - { PHP_VERSION: *php_version, COMPOSER_DEPENDENCY_VERSION: [ "current", "lowest" ] }
  extends: .php

container-build-hash:
  stage: pre-build
  image: "alpine:3"
  script:
    - apk add --no-cache make
    - make container-checksum
  extends: .base
  artifacts:
    reports:
      dotenv: .docker-env

container-build:
  stage: build
  image: "quay.io/podman/stable:v4"
  variables:
    TWINT_SDK_PHP_IMAGE_CACHE: $CI_REGISTRY_IMAGE/php
    # Required to make rootless podman work
    STORAGE_DRIVER: vfs
  script:
    - env
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - >-
      podman build
      --pull=newer
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
      --build-context php_base_image=docker-image://php:$PHP_VERSION-alpine
      --cache-from $TWINT_SDK_PHP_IMAGE_CACHE
      --cache-to $TWINT_SDK_PHP_IMAGE_CACHE
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $TWINT_SDK_PHP_IMAGE_BASE-$PHP_VERSION
      -f Dockerfile
      $PWD
    - podman push $TWINT_SDK_PHP_IMAGE_BASE-$PHP_VERSION
  extends: .php
  needs:
    - job: container-build-hash
      artifacts: true
  only:
    changes:
      - composer.lock
      - Dockerfile
      - .gitlab-ci.yml
      - Makefile

check:
  stage: check
  variables:
    XDEBUG_MODE: coverage
  script:
    - cp ${TWINT_SDK_CI_DOT_ENV} .env
    - $COMPOSER_DEPENDENCY_VERSION == "lowest" && composer update --prefer-lowest || composer install
    - mkdir -p build
    - cat ${TWINT_SDK_CI_CERT} | base64 -d > build/certificate.p12
    - make check
  extends: .php-with-high-low-dependencies
  artifacts:
    reports:
      # Needs GitLab 14.10
      #coverage: build/coverage/clover.xml
      junit: build/junit.xml
      codequality: build/phpstan.json
