services:
  php:
    build:
      additional_contexts:
        php_base_image: docker-image://php:${TWINT_SDK_PHP_VERSION}-alpine
    entrypoint: [sleep, infinity]
    working_dir: /src
    environment:
      - XDEBUG_MODE=coverage
    stop_signal: SIGKILL
    volumes:
      - ./:/src
    depends_on:
        - wiremock

  wiremock:
    image: wiremock/wiremock:3x@sha256:6e9dcfd84cbec2daa7b12f4797a7e7d8f75b5c381df70ed00d2744c4de5360a4
    entrypoint: [/docker-entrypoint.sh, --verbose]

  sphinx:
    image: sphinxdoc/sphinx:7.3.7@sha256:ae9daafd366af9b6caf6ab3ef67c8787cd977c0543d9f7f793bd254f46385515
    entrypoint: [sleep, infinity]
    working_dir: /src
    volumes:
      - ./:/src
    stop_signal: SIGKILL
