services:
  php:
    build:
      additional_contexts:
        php_base_image: docker-image://php:${TWINT_SDK_PHP_VERSION}
    entrypoint: [sleep, infinity]
    working_dir: /src
    environment:
      - XDEBUG_MODE=coverage
    stop_signal: SIGKILL
    volumes:
      - ./:/src
    depends_on:
        - wiremock

  wiremock:
    image: wiremock/wiremock:3x@sha256:16d3091bc5713c0196020602741d2f30c3db9c413522a314b3314b495c6772e4
    entrypoint: [/docker-entrypoint.sh, --verbose]

  sphinx:
    image: sphinxdoc/sphinx:7.4.0@sha256:d122d027fc2b4fbeb38d05fd3ed0e1a97e09a9898fab1178902fd833c6e375ca
    entrypoint: [sleep, infinity]
    working_dir: /src
    volumes:
      - ./:/src
    stop_signal: SIGKILL
