services:
  php:
    build:
      additional_contexts:
        php_base_image: docker-image://php:${TWINT_SDK_PHP_VERSION}
      args:
        TWINT_SDK_PHP_CURL_SSL_ENGINE: ${TWINT_SDK_PHP_CURL_SSL_ENGINE}
    entrypoint: [sleep, infinity]
    working_dir: /src
    environment:
      - XDEBUG_MODE=coverage
    stop_signal: SIGKILL
    volumes:
      - ./:/src
    depends_on:
        - wiremock

  wiremock:
    image: wiremock/wiremock:3x@sha256:9795e41d03213aba2b55ae3ed1c2b37becd297ba14a74dcc29bcc6b3133911bc
    entrypoint: [/docker-entrypoint.sh, --verbose]

  sphinx:
    image: sphinxdoc/sphinx:8.2.3@sha256:8d8bdb4649e6577f20ca9a84ef1e1d46911dc65678fe7908b2e2d3a39508e1c8
    entrypoint: [sleep, infinity]
    working_dir: /src
    volumes:
      - ./:/src
    stop_signal: SIGKILL
