services:
  php:
    build:
      additional_contexts:
        php_base_image: docker-image://php:${TWINT_SDK_PHP_VERSION}
    entrypoint: [sleep, infinity]
    working_dir: /src
    environment:
      - XDEBUG_MODE=coverage
    stop_signal: SIGKILL
    volumes:
      - ./:/src
    depends_on:
        - wiremock

  wiremock:
    image: wiremock/wiremock:3x@sha256:d13997cd7b52583528a766019cfe7d4e91c4d224a67bdaa6f60efbb532f32176
    entrypoint: [/docker-entrypoint.sh, --verbose]

  sphinx:
    image: sphinxdoc/sphinx:8.1.3@sha256:d230ee8a4476f1a91bfee55b502c9c43f41759c97823d8a5b403620bf622c85e
    entrypoint: [sleep, infinity]
    working_dir: /src
    volumes:
      - ./:/src
    stop_signal: SIGKILL
